In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_csv("./cleaned_E-query.csv")

In [3]:
df2 = pd.read_csv("./cleaned_H-query.csv")

In [4]:
df3 = pd.read_csv("./cleaned_D-query.csv")

In [5]:
df4 = pd.read_csv("./cleaned_S-query.csv")

In [6]:
df1

,Unnamed: 0,ALAND,AWATER,BLKGRPCE,COUNTYFP,E11B19001e1,E11B19001e10,E11B19001e11,E11B19001e12,E11B19001e13,...,GEOID_Data,INTPTLAT,INTPTLON,MTFCC,NAMELSAD,OBJECTID,STATEFP,Shape__Area,Shape__Length,TRACTCE
0,0,337300,0,3,59,688,24,34,122,83,...,15000US060590632013,33.648039,-117.906338,G5030,Block Group 3,405,6,4.880021e+05,2966.663021,63201
1,1,686935,0,1,59,1280,85,96,127,262,...,15000US060590638071,33.670797,-117.927415,G5030,Block Group 1,428,6,9.943708e+05,4988.515566,63807
2,2,209303,0,2,59,321,0,30,29,17,...,15000US060590637022,33.640934,-117.921451,G5030,Block Group 2,515,6,3.027684e+05,2518.881817,63702
3,3,323900,0,2,59,417,26,0,31,40,...,15000US060590633022,33.632149,-117.910638,G5030,Block Group 2,641,6,4.684434e+05,2903.018625,63302
4,4,323906,0,1,59,370,9,37,54,38,...,15000US060590633021,33.634940,-117.907865,G5030,Block Group 1,754,6,4.684838e+05,2903.205471,63302
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,71,625083,0,3,59,931,44,10,143,161,...,15000US060590639063,33.660136,-117.904133,G5030,Block Group 3,1734,6,9.046137e+05,4487.184195,63906
72,72,835355,0,3,59,474,0,29,30,54,...,15000US060590639023,33.671315,-117.912966,G5030,Block Group 3,1804,6,1.209237e+06,4531.540365,63902
73,73,426535,0,4,59,632,65,11,78,133,...,15000US060590639024,33.678185,-117.912920,G5030,Block Group 4,1805,6,6.175345e+05,3772.653635,63902
74,74,548656,0,3,59,613,15,17,61,55,...,15000US060590639053,33.660031,-117.911450,G5030,Block Group 3,1807,6,7.940139e+05,3692.445287,63905
75,75,485396,0,4,59,934,22,150,117,242,...,15000US060590639084,33.678813,-117.883348,G5030,Block Group 4,1813,6,7.027679e+05,3831.795981,63908

In [7]:
df2

,Unnamed: 0,ALAND,AWATER,BLKGRPCE,COUNTYFP,FUNCSTAT,GEOID,GEOID_Data,H07B25003e2,H07B25003e3,...,H18B25082e3,INTPTLAT,INTPTLON,MTFCC,NAMELSAD,OBJECTID,STATEFP,Shape__Area,Shape__Length,TRACTCE
0,0,337300,0,3,59,S,60590632013,15000US060590632013,141,547,...,31200000.0,33.648039,-117.906338,G5030,Block Group 3,405,6,4.880021e+05,2966.663021,63201
1,1,686935,0,1,59,S,60590638071,15000US060590638071,301,979,...,73145000.0,33.670797,-117.927415,G5030,Block Group 1,428,6,9.943708e+05,4988.515566,63807
2,2,209303,0,2,59,S,60590637022,15000US060590637022,8,313,...,NaN,33.640934,-117.921451,G5030,Block Group 2,515,6,3.027684e+05,2518.881817,63702
3,3,323900,0,2,59,S,60590633022,15000US060590633022,86,331,...,33780000.0,33.632149,-117.910638,G5030,Block Group 2,641,6,4.684434e+05,2903.018625,63302
4,4,323906,0,1,59,S,60590633021,15000US060590633021,300,70,...,246050000.0,33.634940,-117.907865,G5030,Block Group 1,754,6,4.684838e+05,2903.205471,63302
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,71,625083,0,3,59,S,60590639063,15000US060590639063,296,635,...,33695000.0,33.660136,-117.904133,G5030,Block Group 3,1734,6,9.046137e+05,4487.184195,63906
72,72,835355,0,3,59,S,60590639023,15000US060590639023,0,474,...,NaN,33.671315,-117.912966,G5030,Block Group 3,1804,6,1.209237e+06,4531.540365,63902
73,73,426535,0,4,59,S,60590639024,15000US060590639024,20,612,...,NaN,33.678185,-117.912920,G5030,Block Group 4,1805,6,6.175345e+05,3772.653635,63902
74,74,548656,0,3,59,S,60590639053,15000US060590639053,414,199,...,72425000.0,33.660031,-117.911450,G5030,Block Group 3,1807,6,7.940139e+05,3692.445287,63905
75,75,485396,0,4,59,S,60590639084,15000US060590639084,12,922,...,NaN,33.678813,-117.883348,G5030,Block Group 4,1813,6,7.027679e+05,3831.795981,63908

In [8]:
df3

,Unnamed: 0,ALAND,AWATER,BLKGRPCE,COUNTYFP,D01B01001e1,D01B01001e10,D01B01001e11,D01B01001e12,D01B01001e13,...,GEOID_Data,INTPTLAT,INTPTLON,MTFCC,NAMELSAD,OBJECTID,STATEFP,Shape__Area,Shape__Length,TRACTCE
0,0,337300,0,3,59,1682,12,63,117,57,...,15000US060590632013,33.648039,-117.906338,G5030,Block Group 3,405,6,4.880021e+05,2966.663021,63201
1,1,686935,0,1,59,2999,34,77,78,159,...,15000US060590638071,33.670797,-117.927415,G5030,Block Group 1,428,6,9.943708e+05,4988.515566,63807
2,2,209303,0,2,59,605,0,77,18,32,...,15000US060590637022,33.640934,-117.921451,G5030,Block Group 2,515,6,3.027684e+05,2518.881817,63702
3,3,323900,0,2,59,937,14,95,51,23,...,15000US060590633022,33.632149,-117.910638,G5030,Block Group 2,641,6,4.684434e+05,2903.018625,63302
4,4,323906,0,1,59,903,0,0,8,24,...,15000US060590633021,33.634940,-117.907865,G5030,Block Group 1,754,6,4.684838e+05,2903.205471,63302
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,71,625083,0,3,59,2370,25,77,227,77,...,15000US060590639063,33.660136,-117.904133,G5030,Block Group 3,1734,6,9.046137e+05,4487.184195,63906
72,72,835355,0,3,59,1240,73,31,154,36,...,15000US060590639023,33.671315,-117.912966,G5030,Block Group 3,1804,6,1.209237e+06,4531.540365,63902
73,73,426535,0,4,59,1625,149,121,17,0,...,15000US060590639024,33.678185,-117.912920,G5030,Block Group 4,1805,6,6.175345e+05,3772.653635,63902
74,74,548656,0,3,59,1637,45,48,127,29,...,15000US060590639053,33.660031,-117.911450,G5030,Block Group 3,1807,6,7.940139e+05,3692.445287,63905
75,75,485396,0,4,59,1475,19,208,320,118,...,15000US060590639084,33.678813,-117.883348,G5030,Block Group 4,1813,6,7.027679e+05,3831.795981,63908

In [9]:
df4

,Unnamed: 0,ALAND,AWATER,BLKGRPCE,COUNTYFP,FUNCSTAT,GEOID,GEOID_Data,INTPTLAT,INTPTLON,...,S08B21001e1,S08B21001e2,S19B28008e10,S19B28008e2,S19B28008e4,S19B28008e9,STATEFP,Shape__Area,Shape__Length,TRACTCE
0,0,337300,0,3,59,S,60590632013,15000US060590632013,33.648039,-117.906338,...,1239,65,0,1682,1605,77,6,4.880021e+05,2966.663021,63201
1,1,686935,0,1,59,S,60590638071,15000US060590638071,33.670797,-117.927415,...,2373,142,0,2999,2945,54,6,9.943708e+05,4988.515566,63807
2,2,209303,0,2,59,S,60590637022,15000US060590637022,33.640934,-117.921451,...,547,18,111,494,327,167,6,3.027684e+05,2518.881817,63702
3,3,323900,0,2,59,S,60590633022,15000US060590633022,33.632149,-117.910638,...,906,10,4,933,927,6,6,4.684434e+05,2903.018625,63302
4,4,323906,0,1,59,S,60590633021,15000US060590633021,33.634940,-117.907865,...,641,37,65,831,805,26,6,4.684838e+05,2903.205471,63302
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,71,625083,0,3,59,S,60590639063,15000US060590639063,33.660136,-117.904133,...,2076,85,236,1884,1846,38,6,9.046137e+05,4487.184195,63906
72,72,835355,0,3,59,S,60590639023,15000US060590639023,33.671315,-117.912966,...,1053,123,52,1188,903,185,6,1.209237e+06,4531.540365,63902
73,73,426535,0,4,59,S,60590639024,15000US060590639024,33.678185,-117.912920,...,1432,14,109,1516,1360,156,6,6.175345e+05,3772.653635,63902
74,74,548656,0,3,59,S,60590639053,15000US060590639053,33.660031,-117.911450,...,1346,68,151,1450,1337,113,6,7.940139e+05,3692.445287,63905
75,75,485396,0,4,59,S,60590639084,15000US060590639084,33.678813,-117.883348,...,1377,60,0,1475,1390,0,6,7.027679e+05,3831.795981,63908

In [10]:
common_list = ['Unnamed: 0', 'ALAND', 'AWATER', 'BLKGRPCE', 'COUNTYFP', 'FUNCSTAT',
       'GEOID', 'GEOID_Data', 'INTPTLAT', 'INTPTLON', 'MTFCC', 'NAMELSAD',
       'OBJECTID', 'STATEFP', 'Shape__Area', 'Shape__Length', 'TRACTCE']

In [11]:
df = df1.merge(df2, on=common_list, how="inner")

In [12]:
df = df.merge(df3,on=common_list, how="inner")

In [13]:
df = df.merge(df4,on=common_list, how="inner")

In [14]:
df

,Unnamed: 0,ALAND,AWATER,BLKGRPCE,COUNTYFP,E11B19001e1,E11B19001e10,E11B19001e11,E11B19001e12,E11B19001e13,...,S07B15003e22,S07B15003e23,S07B15003e24,S07B15003e25,S08B21001e1,S08B21001e2,S19B28008e10,S19B28008e2,S19B28008e4,S19B28008e9
0,0,337300,0,3,59,688,24,34,122,83,...,411,38,38,11,1239,65,0,1682,1605,77
1,1,686935,0,1,59,1280,85,96,127,262,...,810,282,20,10,2373,142,0,2999,2945,54
2,2,209303,0,2,59,321,0,30,29,17,...,112,92,28,0,547,18,111,494,327,167
3,3,323900,0,2,59,417,26,0,31,40,...,293,131,20,0,906,10,4,933,927,6
4,4,323906,0,1,59,370,9,37,54,38,...,282,103,10,9,641,37,65,831,805,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,71,625083,0,3,59,931,44,10,143,161,...,566,153,13,0,2076,85,236,1884,1846,38
72,72,835355,0,3,59,474,0,29,30,54,...,113,13,0,0,1053,123,52,1188,903,185
73,73,426535,0,4,59,632,65,11,78,133,...,196,127,47,0,1432,14,109,1516,1360,156
74,74,548656,0,3,59,613,15,17,61,55,...,418,120,14,12,1346,68,151,1450,1337,113
75,75,485396,0,4,59,934,22,150,117,242,...,454,137,12,0,1377,60,0,1475,1390,0

In [15]:
df.to_csv("../merged.csv")